### ISSUE TITLE
AtCoder Practice 6-1

### ISSUE THREAD

**Issue by shsaSF** [yantszlok/PHPtest#1]
# 問題

入力される文字列が全て同じ文字であったら "OK" を出力し、一文字でも違う文字が存在すれば、"NG"と表示するプログラムを書きなさい

# 入力例
- aaaaaa
    -  "OK"
- aaaaba
    - "NG"
- a
   - "OK"
- aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
   - "OK"
- aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaazaaaaaaa
   - "NG"

**Comment by yantszlok** [comment]
atcoderのファイルにpushしました。
