### ISSUE TITLE
atcoder7: 空白区切り文字の一番最初の文字しか受け入れていない

### ISSUE THREAD

**Issue by shsaSF** [yantszlok/PHPtest#2]
https://github.com/yantszlok/PHPtest/blob/1e883ae0ab94c3e5a2ffabfb93dc5cf4ce906d1b/atcoder/atcoder7.php#L3

```
# 入力例
3
1 2 5

# $A
string(1) "1"

# $Array
array(1) {
  [0]=>
  string(1) "1"
}
```

例えば、

2
1 2

と入力すると、「 偶数であるものは全て、3 または 5 で割り切れる。」に適合しません。

なぜなら、1 のみが対象となっているためです。

**Comment by shsaSF** [comment]
文字列入力の場合、fscanf より、fgets のほうがいいかもです。
https://qiita.com/aoaoao/items/b07df5f57f5959489b9d

**Comment by yantszlok** [comment]
教えていただきありがとうございます
fgetsに書き換えました。
