### ISSUE TITLE
AtCoder8: index -1 でエラーが発生する

### ISSUE THREAD

**Issue by shsaSF** [yantszlok/PHPtest#3]
https://github.com/yantszlok/PHPtest/blob/1e883ae0ab94c3e5a2ffabfb93dc5cf4ce906d1b/atcoder/atcoder8.php#L11

index 0 と index -1 の比較をしてしまっており、エラーが発生します。

**Comment by yantszlok** [comment]
修正しました。
for文の初期化を $i = 1 にしました。
配列[ 1 ]からfor文を回すため、最後に echo $ans + 1 にしました。
配列[ 0 ]を最初からスライムの数に入れるためです。
